/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BankRouteImport } from './routes/bank'
import { Route as DriversRouteImport } from './routes/drivers'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as PayoutsRouteImport } from './routes/payouts'
import { Route as FleetsRouteImport } from './routes/fleets'
import { Route as LoansRouteImport } from './routes/loans'
import { Route as ReceiptsRouteImport } from './routes/receipts'
import { Route as RentRouteImport } from './routes/rent'
import { Route as ManageDriversRouteImport } from './routes/manage-drivers'
import { Route as StatementRouteImport } from './routes/statement'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BankRoute = BankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversRoute = DriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const PayoutsRoute = PayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetsRoute = FleetsRouteImport.update({
  id: '/fleets',
  path: '/fleets',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansRoute = LoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const RentRoute = RentRouteImport.update({
  id: '/rent',
  path: '/rent',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageDriversRoute = ManageDriversRouteImport.update({
  id: '/manage-drivers',
  path: '/manage-drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const StatementRoute = StatementRouteImport.update({
  id: '/statement',
  path: '/statement',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bank': typeof BankRoute
  '/drivers': typeof DriversRoute
  '/expenses': typeof ExpensesRoute
  '/payouts': typeof PayoutsRoute
  '/fleets': typeof FleetsRoute
  '/loans': typeof LoansRoute
  '/receipts': typeof ReceiptsRoute
  '/rent': typeof RentRoute
  '/manage-drivers': typeof ManageDriversRoute
  '/statement': typeof StatementRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bank': typeof BankRoute
  '/drivers': typeof DriversRoute
  '/expenses': typeof ExpensesRoute
  '/payouts': typeof PayoutsRoute
  '/fleets': typeof FleetsRoute
  '/loans': typeof LoansRoute
  '/receipts': typeof ReceiptsRoute
  '/rent': typeof RentRoute
  '/manage-drivers': typeof ManageDriversRoute
  '/statement': typeof StatementRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bank': typeof BankRoute
  '/drivers': typeof DriversRoute
  '/expenses': typeof ExpensesRoute
  '/payouts': typeof PayoutsRoute
  '/fleets': typeof FleetsRoute
  '/loans': typeof LoansRoute
  '/receipts': typeof ReceiptsRoute
  '/rent': typeof RentRoute
  '/manage-drivers': typeof ManageDriversRoute
  '/statement': typeof StatementRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bank'
    | '/drivers'
    | '/expenses'
    | '/payouts'
    | '/fleets'
    | '/loans'
    | '/receipts'
    | '/rent'
    | '/manage-drivers'
    | '/statement'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bank'
    | '/drivers'
    | '/expenses'
    | '/payouts'
    | '/fleets'
    | '/loans'
    | '/receipts'
    | '/rent'
    | '/manage-drivers'
    | '/statement'
  id:
    | '__root__'
    | '/'
    | '/bank'
    | '/drivers'
    | '/expenses'
    | '/payouts'
    | '/fleets'
    | '/loans'
    | '/receipts'
    | '/rent'
    | '/manage-drivers'
    | '/statement'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BankRoute: typeof BankRoute
  DriversRoute: typeof DriversRoute
  ExpensesRoute: typeof ExpensesRoute
  PayoutsRoute: typeof PayoutsRoute
  FleetsRoute: typeof FleetsRoute
  LoansRoute: typeof LoansRoute
  ReceiptsRoute: typeof ReceiptsRoute
  RentRoute: typeof RentRoute
  ManageDriversRoute: typeof ManageDriversRoute
  StatementRoute: typeof StatementRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank': {
      id: '/bank'
      path: '/bank'
      fullPath: '/bank'
      preLoaderRoute: typeof BankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payouts': {
      id: '/payouts'
      path: '/payouts'
      fullPath: '/payouts'
      preLoaderRoute: typeof PayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleets': {
      id: '/fleets'
      path: '/fleets'
      fullPath: '/fleets'
      preLoaderRoute: typeof FleetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans': {
      id: '/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof LoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent': {
      id: '/rent'
      path: '/rent'
      fullPath: '/rent'
      preLoaderRoute: typeof RentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-drivers': {
      id: '/manage-drivers'
      path: '/manage-drivers'
      fullPath: '/manage-drivers'
      preLoaderRoute: typeof ManageDriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statement': {
      id: '/statement'
      path: '/statement'
      fullPath: '/statement'
      preLoaderRoute: typeof StatementRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BankRoute: BankRoute,
  DriversRoute: DriversRoute,
  ExpensesRoute: ExpensesRoute,
  PayoutsRoute: PayoutsRoute,
  FleetsRoute: FleetsRoute,
  LoansRoute: LoansRoute,
  ReceiptsRoute: ReceiptsRoute,
  RentRoute: RentRoute,
  ManageDriversRoute: ManageDriversRoute,
  StatementRoute: StatementRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
